### ISSUE TITLE
Change medium's responce template

### ISSUE THREAD

**Issue by DracoL1ch** [TheOtherRolesAU/TheOtherRoles#312]
Would it make more sense and readability if:
Instead of "%s is %s (%Ghost_name)" we had
"%Ghost_name said %s %s"
Right now some newbies get confused when they see something like 'My killer is Evil Guesser (L1ch)' assuming L1ch is the Evil Guesser. It takes them some time to get into the mechanic, while we dont really need those brackets to be at the end.

**Comment by JustASysAdmin** [comment]
I mean......that's a problem of reading no? I agree the parentheses is vague, but it says "my killer". There isn't much that can be done if people just read "role is evil Guesser" and not the "my killers" part before it.
