### ISSUE TITLE
[Suggestion] Allow neutral roles to see a venting engineer

### ISSUE THREAD

**Issue by Kateba72** [TheOtherRolesAU/TheOtherRoles#321]
A neutral role (e.g. Jackal, Vulture) with access to vents should be able to see whether a engineer is currently in the vents. As these roles also don't want to be caught venting, they should get the same blue outline as imposters when the vent is occupied.

**Comment by K3ndoo** [comment]
Thanks for this idea, but it didn't make the cut.
