### ISSUE TITLE
[Suggestion] Support translation in JSON or CSV

### ISSUE THREAD

**Issue by MapleEve** [TheOtherRolesAU/TheOtherRoles#353]
**Is your feature request related to a problem? Please describe.**
No, but the other mods had developed such function and allow most of translation group to submit translations.

**Describe the solution / role you'd like**
An excel to json would work. The translation words are easy to maintain.

**Describe alternatives you've considered**
Display keys hardcode in CS file is hard to catch up with version updates.

**Additional context**
None.

**Comment by K3ndoo** [comment]
Thanks, but too much work for now.
