### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by Deikekek** [TheOtherRolesAU/TheOtherRoles#354]
**Describe the bug**
Werde jedes Mal gekicked, wenn der Host nicht vor mir die nächste Runde startet
**To Reproduce**
1. Runde ist beendet
2. Klicke auf 'Continue'
3. Klicke auf 'Play again'
4. 'Waiting for host' 
5. 

**Expected behavior**
Nach 'Waiting for host' direkt in die Nächste Runde starten können

**Screenshots**

**System (please complete the following information):**
 - OS: [Windows 10]
 - Among Us Version [v2022.3.29s]
 - TheOtherRoles Version [4.1.3]
![1](https://user-images.githubusercontent.com/105947305/169603481-64af7348-d4b9-47a0-87ff-b160fe4139cf.PNG)
![2](https://user-images.githubusercontent.com/105947305/169603489-cc3f9de0-7b8a-46a3-a602-0c5fc975019b.PNG)

**Comment by dwd0tcom** [comment]
It's pretty hard to reproduce this issue. Did you try a clean install?

**Comment by Mallaris** [comment]
is this still happening with version 4.1.4?

**Comment by Deikekek** [comment]
No, since the last Update the Bug is fixed. Thanks for asking 

Gesendet von Yahoo Mail auf Android 
 
  Am Mi., Juni 8, 2022 at 20:23 schrieb ***@***.***>:   


is this still happening with version 4.1.4?
