### ISSUE TITLE
[Bug Report] System.Collections.Generic.KeyNotFoundException: The given key '1383' was not present in the dictionary.

### ISSUE THREAD

**Issue by MapleEve** [TheOtherRolesAU/TheOtherRoles#358]
**Describe the bug**
If a user DC in the middle of a game. When the game ends, he cannot join the game even if s/he rerun the AU.
Host will receive "No mod" warning for that player.

**To Reproduce**
Players Dictionary of NerID won't update if a game started. or other issue due to Cached added in this version.

**Expected behavior**
fix the code

**Screenshots**
![image](https://user-images.githubusercontent.com/1845053/170638988-480f2456-6423-47b8-a223-32d09997c45d.png)
added logger to check which function is broken,
![image](https://user-images.githubusercontent.com/1845053/170639121-d7c32c31-d5d0-4891-aaf2-c78d53ec1d3e.png)
then get this error

**Additional context**
own translated fork
https://github.com/MapleEve/TheOtherRoles_RamboPlay/commit/49f2a775d7d5187f10c530012c3746b838fad9a4

**Comment by K3ndoo** [comment]
If this problem still occurs, please let us know in our Discord. Thanks for the report!
