### ISSUE TITLE
"The host no or a different version of the other roles wou will be kicked" I'm not sure if its a bug or the other players just havent really updated theirs.[Bug Report]

### ISSUE THREAD

**Issue by GianMire** [TheOtherRolesAU/TheOtherRoles#362]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Among Us Version [e.g. v2021.11.15s]
 - TheOtherRoles Version [e.g. v3.3.3]

**Additional context**

**Comment by MapleEve** [comment]
this has been reported since Cached added
