### ISSUE TITLE
[Suggestion] If there is a sherrif alive the game shouldn't end

### ISSUE THREAD

**Issue by kristibektashi** [TheOtherRolesAU/TheOtherRoles#365]
If there is a sherrif alive the game shouldn't end if there are 2 people left or if there is an equal number of crewmates and impostors since sherrif could technically still win

This should be an option that you can turn on or off in the settings since not everyone might want this feature

**Comment by K3ndoo** [comment]
Thanks for this idea, but it didn't make the cut (for now).
