### ISSUE TITLE
[Suggestion] A new Forensics Role.

### ISSUE THREAD

**Issue by Ovindu1u** [TheOtherRolesAU/TheOtherRoles#367]
When you report a body the role of the dead person will be revealed.

**Comment by K3ndoo** [comment]
So, a better version of the Medium? What else should this role have/do? Could be pretty lame if you never have a chance to report a body.

**Comment by Ovindu1u** [comment]
To increase the chance of finding a body, vitals could show which room the body is or which direction relative to the vitals or a mobile vitals device.

**Comment by K3ndoo** [comment]
So a Tracker/Hacker/Medium?

**Comment by GalGreenfield** [comment]
I think this should come at a cost: having a risk of dying and/or being sussed.

And I think a good way to implement this is to need to stand enough around a body to reveal "clues", which I think could look cool with an animation - or just a timer could be added.

**Comment by Ovindu1u** [comment]
> I think this should come at a cost: having a risk of dying and/or being sussed.
> 
> And I think a good way to implement this is to need to stand enough around a body to reveal "clues", which I think could look cool with an animation - or just a timer could be added.

Yeah having to stand there for sometime would be good.

**Comment by K3ndoo** [comment]
Thanks for this idea, but it didn't make the cut.
