### ISSUE TITLE
[Suggestion] New Role: Reviver

### ISSUE THREAD

**Issue by ruelluna** [TheOtherRolesAU/TheOtherRoles#374]
A Reviver has x2(double) of tasks. When tasks are finished, Reviver can choose who to revive and come back at the game to reveal who killed him/her. 

I love to see Toast and the gang play this. :)

**Comment by K3ndoo** [comment]
Well you'll never see this then. Sorry. No reviving.

**Comment by alexasterisk** [comment]
A better solution to this would be an implementation of Altruist from Town Of Us. The Altruist sacrifices their own life when they're on top of a body and after three seconds that player gets revived. The non-good alignment killing roles would then get a flash and an arrow pointing towards the player that was altruisted. The role you are asking for is way too overpowered and broken.

Over all though, people don't really like the ability of revival in Among Us, usually Altruist isn't played with and personally I don't like it. Instead, for game-play post death I'd recommend semi-ghost roles like the Phantom from Town Of Us.

**Comment by K3ndoo** [comment]
No reviving in any form.

**Comment by K3ndoo** [comment]
I did. Still no reviving in any form.
