### ISSUE TITLE
[Bug Report] Mod not working with new Among Us update

### ISSUE THREAD

**Issue by SHADOWLITNESS** [TheOtherRolesAU/TheOtherRoles#375]
Mod not working with new Among Us update
Played it a few hours ago before the update. 
After the update it stopped working

**Comment by pangkoi101** [comment]
hope this gets fixed soon :(

**Comment by forentfraps** [comment]
![image](https://user-images.githubusercontent.com/29946764/175281646-34a6819d-2214-4dd7-baed-cdc86c11329c.png)


Select Public-previous beta, the mod works properly with it.
Until the mod is patched, that is the only viable solution i found

@SHADOWLITNESS @pangkoi101
