### ISSUE TITLE
[Suggestion] More crewmate roles can become task-powered

### ISSUE THREAD

**Issue by Patashu** [TheOtherRolesAU/TheOtherRoles#377]
It strikes me that crewmembers are supposed to do tasks (and this is in fact one of the things that's supposed to make you look crew-aligned, and should be faked by imposters, etc), but in a mod like this a lot of cool, flashy, powerful roles don't require you to advance the normal win condition even the tiniest bit, but some like Swapper and Hacker do. If lobbies go long enough without many task wins, then it can become a habit to not bother doing them since it won't matter. I wonder how the game would play if most to all crewmember roles required doing tasks to refuel them? 

This would require a lot of thinking and work, and I'm not sure it's something people *want*, but throwing it out there in case it inspires.

**Comment by K3ndoo** [comment]
I'm constantly trying to find a way to make people do their tasks since this is an issue for me as well.
