### ISSUE TITLE
Crashes after running first time

### ISSUE THREAD

**Issue by torridgristle** [TheOtherRolesAU/TheOtherRoles#379]
I installed the mod and ran Among Us (it took over a GiB of RAM, not sure if that's a sign of a problem), closed it from within the game, and then tried to run it again. It gets to the Innersloth logo, fades out, the mod icon appears top-right, and then it crashes and says "Collecting from unknown thread".
Here's the generated crash dump and log. [Crash_2022-06-24_211412911.zip](https://github.com/Eisbison/TheOtherRoles/files/8980732/Crash_2022-06-24_211412911.zip)

**Comment by torridgristle** [comment]
It worked once again after this, I didn't change anything, and then it went back to crashing. In case the crash dumps and logs are any different, here's two more.
[Crashes.zip](https://github.com/Eisbison/TheOtherRoles/files/8980739/Crashes.zip)

**Comment by K3ndoo** [comment]
There's currently no fix for this problem.
