### ISSUE TITLE
[Bug Report] Moving Locally only

### ISSUE THREAD

**Issue by Lakriis** [TheOtherRolesAU/TheOtherRoles#380]
**Describe the bug**
I'm Only able to move Locally, for everyone else i'm standing or slow walking in same spot i spawn in!
everything i do is local only, i tested this by killing the entire server but the game kept going
i've tried to reinstall everything but still come down to the same issue. this only started on the newest update
 - Among Us Version v2022.6.21s
 - TheOtherRoles Version 4.1.5

**Comment by Lakriis** [comment]
This only occurs with the mod btw! i've tried running among us alone with CrewLink and it works completely fine

**Comment by JustASysAdmin** [comment]
Please ensure you have everything updates. AU, TOR, and Submerged.

Then make sure EVERYONE does this.

**Comment by K3ndoo** [comment]
What was said before. You need a clean and fresh installation of the mod. If you need a guide on how to do it. Check the github page or our Discord.

**Comment by K3ndoo** [comment]
I highly doubt that. :)
