### ISSUE TITLE
Unplayable Lag After the Update

### ISSUE THREAD

**Issue by pangkoi101** [TheOtherRolesAU/TheOtherRoles#381]
For some reason some crewmates are just afking in the cafeteria and on their screen the other characters are teleporting.

**Comment by hawk4031** [comment]
I'm seconding this problem. I did a completely fresh install and made sure to download the latest files and while I can run around and do things, everyone says that I just sit in one area the whole round.

**Comment by gendelo3** [comment]
The problem is possibly caused by a mismatch in the Submerged version. Make sure everyone in you group either has NO submerged.dll in BepinEx/plugins, or everyone has the same (newest) version.
