### ISSUE TITLE
[Suggestion] Role: Genius & Evil Genius

### ISSUE THREAD

**Issue by GalGreenfield** [TheOtherRolesAU/TheOtherRoles#383]
## Role idea: Genius (Crerwmate) and Evil Genius (Impostor).

![](https://user-images.githubusercontent.com/5772368/176798344-3b84a578-e8af-4f29-89df-99fb1f3fbbf3.jpg)
_image taken from: https://www.youtube.com/watch?v=qjUW3OXinjg_

#### Prove yourself as the ultimate big brain! 
Both the Genius and the Evil Genius have regular vision and speed, and can't kill, _but_, they can open up a list of roles for each player. If they spend a certain amount of time with vision of a nearby player they choose, they list off random a role that someone is **not**. They can also list roles off manually.

The Genius and the Evil Genius can vote off players like Guessers (that also means that if you're wrong you die - for when you _really_ are 5head). So the longer they're alive, the more confident they will become of people's roles. But the catch is that they will grow one brain cell every time they use their _Big Brain_ ability (indicated by a brain over whatever they're wearing growing slightly), making them progressively slower, so the more time passes, the more they'll be easily identified - and killed, too. So, Impostors - better identify and kill the Genius early, and Crewmates - make sure you're not mistrusting the Evil Genius.

### Notes
- Manual marking of roles will have an indication (so people don't just mark roles manually and forget about it and not have them randomly listed off).
- Their brain will be the color of their body and will grow on top of whatever they're wearing (or not wearing) on their head, just to make it simpler to implement graphically.
- There can be some conditions and rules set for when their brains start to grow and how quickly.
- For balancing, there could be a cooldown for when they can start "gathering information" on someone. Do note that if someone suddenly evades them - that's sus. You're a genius, you should figure out what that implies. 
- For balancing, the amount of time set for "gathering information" on someone to list off a possible role could be adjusted.

Finally, all those Among Us "geniuses" can show us just how much of a "genius" they are (or maybe that they're _actual_ big-brain).

**Comment by K3ndoo** [comment]
Thanks for this idea, but it didn't make the cut.

**Comment by GalGreenfield** [comment]
> Thanks for this idea, but it didn't make the cut.

Hi, can you please tell me why? I have other mod ideas and would like to know how you judge role ideas so I don't end up spending time coming up with ones and designing ones you wouldn't like to develop.
