### ISSUE TITLE
Occasional invalid address crash

### ISSUE THREAD

**Issue by GodTamIt** [TheOtherRolesAU/TheOtherRoles#385]
**Describe the bug**
Occasionally, the game crashes with an attempt to access invalid address.

Logs are here: [Crash.zip](https://github.com/Eisbison/TheOtherRoles/files/9060832/Crash.zip)

**To Reproduce**
1. Use game for a long enough period of time.
2. Notice game crashes randomly with logs captured.

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 10
 - Among Us Version: v2022.6.21s
 - TheOtherRoles Version: v4.1.5

**Comment by K3ndoo** [comment]
If this problem still occurs, please let us know in our Discord! Thanks for the report.
