### ISSUE TITLE
[Bug Report] Cosmetics are visible outside the chat area

### ISSUE THREAD

**Issue by RobinRMC** [TheOtherRolesAU/TheOtherRoles#386]
**The bug:**
Cosmetics are visible outside the chat area.

**To reproduce:**
Chat

**Expected behavior:**
It not to happen.

**Screenshots:**
https://imgur.com/a/jbQ5KvO

**System:**
 - Operating System: Windows 10
 - Among Us Version: v2022.6.21s
 - TheOtherRoles Version: v4.1.5

**Additional context:**
No.

**Comment by K3ndoo** [comment]
Vanilla Bug.
