### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by RosieRHea** [TheOtherRolesAU/TheOtherRoles#390]
**Describe the bug**
Upon first playing the most recent version, a number of lobby members are green instead of their chosen colour, In meeting they appear as this weird inverted yellow-orange colour, then after meetings they appear as a black colour. I've restarted the game and played with the graphics settings and it didn't make a difference.

**Expected behavior**

**Screenshots**
In lobby/first round

![image](https://user-images.githubusercontent.com/110130364/181365643-8414a10f-7afb-410a-bbcb-420a5f0b17b1.png)

In meeting

![image](https://user-images.githubusercontent.com/110130364/181366721-665dd1f8-baee-4607-a759-c1ee3f7ce3c9.png)

After meeting

![image](https://user-images.githubusercontent.com/110130364/181366807-ffc4bd6a-ac19-48f7-b195-54783fc3092e.png)

**System (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Among Us Version [e.g. v2021.11.15s]
 - TheOtherRoles Version [e.g. v3.3.3]

**Additional context**

**Comment by RosieRHea** [comment]
Windows 10, v4.1.6,

**Comment by K3ndoo** [comment]
Buggy Lobby. Open a new one.
