### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by MoltenGlitch** [TheOtherRolesAU/TheOtherRoles#391]
**Describe the bug**

This
![Bug](https://user-images.githubusercontent.com/110196522/181615997-62c4b1b0-fd57-4e81-bbdb-1f2291dcf077.png)
Is a glitch that happened when i reported a body and called a meeting

**Comment by K3ndoo** [comment]
Should be your lobby that was bugged. We couldn't reproduze this bug.
