### ISSUE TITLE
[Bug] Handcuffs remain after death

### ISSUE THREAD

**Issue by DracoL1ch** [TheOtherRolesAU/TheOtherRoles#394]
Ghost suffers of Handcuffs debuff causing camera buttons being locked

**Comment by K3ndoo** [comment]
This isn't a bug. It's intended.

**Comment by DracoL1ch** [comment]
how is it intended? whats the point?

**Comment by gendelo3** [comment]
There are at least two reasons it is this way:

- The team thinks it's funny to hear other players complain about being handcuffed, and it causes no harm to the gameplay
- It would be (a little) extra work to end the handcuff duration early and it's just not worth changing it.

**Comment by DracoL1ch** [comment]
You can not hear ghosts, so irrelevant
All the extra work is one more line to remove handcuffed state from player on death event.
This is minor bug, but its a bug

**Comment by K3ndoo** [comment]
And it's not a bug since it's intended. So, won't be changed. :)
