### ISSUE TITLE
Security Guard Buff for MiraHQ

### ISSUE THREAD

**Issue by Sableye** [TheOtherRolesAU/TheOtherRoles#396]
**Is your feature request related to a problem? Please describe.**
Currently the Security Guard can only seal vents in Mira, whilst they can set cams on every other map as well.

**Describe the solution / role you'd like**
Give the role the ability to place some sensors for the door log. Depending on balancing it might take more than two charges, as logssensors may be pretty strong. This could spice up the game. 

**Describe alternatives you've considered**
Alternatively add there timestamps on the doorlog, so the security guard knows when someone passed the doors

**Comment by K3ndoo** [comment]
1. I think this would cause too much work and effort for such a little impact.
2. Sealing vents on a map like Mira is pretty strong.

And please submit suggestions in our Discord, since it's easier to track AND it could also be discussed further if necessary.
Thanks in advance.
