### ISSUE TITLE
[Bug Report] Bloody modifier takes killer's color instead of the victim's

### ISSUE THREAD

**Issue by DracoL1ch** [TheOtherRolesAU/TheOtherRoles#402]
Title

**Comment by K3ndoo** [comment]
Already fixed with the next update. Please submit bugs like that in our discord. It's easier to track. :)

**Comment by DracoL1ch** [comment]
> Already fixed with the next update. Please submit bugs like that in our discord. It's easier to track. :)
if only I wasnt banned there, sure
