### ISSUE TITLE
[Bug Report] Bloody shows wrong trail color

### ISSUE THREAD

**Issue by Bubunator** [TheOtherRolesAU/TheOtherRoles#403]
**Describe the bug**
If a player with the "Bloody" modifier gets killed, the killer will leave a blood trail of his own color instead of the color from the killed player.

**Expected behavior**
Quote from the Readme: If killed, the Bloody Modifier will leave a trail for x-seconds on their killer. The trail will have the color of the killed person. Impostor, Neutral or Crewmate roles can have this Modifier."

**Screenshots**

**System (please complete the following information):**
 - Windows 11
 -Latest Among Us Version
 - TheOtherRoles Version v4.1.7

**Additional context**
Can create sceenshots if required

**Comment by K3ndoo** [comment]
Thanks btw for this report. This should be fixed with the next update!
