### ISSUE TITLE
[Bug Report]I’ve been tryna play this mod with others that don’t have it installed and I won’t give them access to the mod when I’m host anyway to get past this 

### ISSUE THREAD

**Issue by CACTUSCORP92** [TheOtherRolesAU/TheOtherRoles#407]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Among Us Version [e.g. v2021.11.15s]
 - TheOtherRoles Version [e.g. v3.3.3]

**Additional context**

**Comment by gendelo3** [comment]
Wrong mod. Everyone needs to have TheOtherRoles installed.
