### ISSUE TITLE
[Bug Report] Key binds are hardcoded

### ISSUE THREAD

**Issue by Dadoum** [TheOtherRolesAU/TheOtherRoles#409]
**Describe the bug**
Keyboard binds are hard coded inside the mod code, leading to conflicting keys on some keyboard layouts, and it is breaking controller support.

**To Reproduce**
Example with the Q key (left key in the equivalent of WASD in AZERTY keyboard):
1. Set Q key for left and A key for kill action.
2. Spawn in Sheriff or any custom role implementing a kill action.
3. Go left and accidentally trigger the action.

**Expected behavior**
The mod should respect keyboard binds that are in the game when possible.

**System (please complete the following information):**
 - OS: Fedora 36 through Wine 
 - Among Us Version: v2022.8.24
 - TheOtherRoles Version: Still present at 4.1.7

**Additional context**
Technically a duplicate of #244 which has been closed without being fixed. I made a quick fix in #347.

**Comment by ccir2429** [comment]
As far as I know, it is not considered a bug. 
You could try setting up your keyboard to qwerty for whenever you are playing among us.

**Comment by Dadoum** [comment]
It is still a bug (since it does not follow the Among Us scheme).

And anyway I fixed it in my fork.

**Comment by Dadoum** [comment]
@K3ndoo has it been finally resolved?
