### ISSUE TITLE
[Bug Report] Medium + Lover

### ISSUE THREAD

**Issue by FunAwaits** [TheOtherRolesAU/TheOtherRoles#410]
**Describe the bug**
When I was the medium and a lover, I couldn't see what the body was trying to tell me. Even during the meeting phase.  I did open chat before I talked to the body though; no clue if that was related.

**Expected behavior**
I expected to see what the body was trying to tell me as a lover and medium.

**System (please complete the following information):**
 - OS: Windows 11
 - Among Us Version v4.1.7
 - TheOtherRoles Version v2022.9.20

**Comment by K3ndoo** [comment]
Maybe the dead player dc'd? If this still occurs in 4.2.0, please open a new bug report.
