### ISSUE TITLE
[Bug Report] Trapper reporting

### ISSUE THREAD

**Issue by Vayra** [TheOtherRolesAU/TheOtherRoles#413]
**Describe the bug**
When placing multiple traps that are triggered in the same round  only information from one trap is revealed. 
Instead the second trap reactivates next round and information is displayed about it in a later round based on the new information.
**To Reproduce**
As trapper:

1. Place a trap and have enough people trigger it
2. place a second trap and have enough people trigger it
3. call meeting
4. should only see information from one trap

**Expected behavior**
Information from both traps should be displayed. For example if roles are revealed it should reveal the following:
Trap 1:
Sidekick
Mayor
Trap 2:
Sidekick
Sheriff

**System (please complete the following information):**
 - OS: Win 10
 - Among Us Version [e.g. v2022.10.25]
 - TheOtherRoles Version [e.g. v4.2.0]

**Additional context**

**Comment by K3ndoo** [comment]
I guess that not enough people triggered your placed traps. This works as intended

![image](https://user-images.githubusercontent.com/92563515/201254238-e1e1b596-c597-48ea-a2a8-dd8081fb7110.png)
![image](https://user-images.githubusercontent.com/92563515/201254251-c69f3a92-2786-4ce7-83a1-b98f7d42207d.png)
![image](https://user-images.githubusercontent.com/92563515/201254260-501faab5-b754-487c-b6a6-76c554e80533.png)
