### ISSUE TITLE
Maybe I found a mod that violates the GPL.

### ISSUE THREAD

**Issue by Dekokiyo** [TheOtherRolesAU/TheOtherRoles#416]
Long time no see,
I also asked a question about the licenses before.
Same thing today.

This is your mod Code.
![image](https://user-images.githubusercontent.com/97837904/199245162-ca4284ce-c76b-49bd-bcd9-953669fd2acc.png)

And this is the code for the mod called Agartha from [SuperNewRoles](https://github.com/ykundesu/SuperNewRoles)
![image](https://user-images.githubusercontent.com/97837904/199245118-6708642b-5f7e-4c7f-aabd-9fb98396bcfc.png)

Yesterday, I received an image and description in my Twitter DM.
I'm not sure if this is correct, but I let you know.

**Comment by gendelo3** [comment]
The code is the same, because that mod is apparently entirely based on TheOtherRoles.

They give credit to TheOtherRoles in their English Readme file, and since their repo is also under GPLv3 it should be fine.

**Comment by Dekokiyo** [comment]
Yeah, SuperNewRoles is not violating.
But, A mod called Agartha, a map mod dedicated to SuperNewRoles, is in violation.
This mod has a separate repository and is private.
And, No License.
