### ISSUE TITLE
[Bug Report] Erase has failures sometimes not clearing roles

### ISSUE THREAD

**Issue by DracoL1ch** [TheOtherRolesAU/TheOtherRoles#418]
https://www.twitch.tv/videos/1640471302?t=0h54m42s
This timestamp, I clearly click Erase on the body

https://www.twitch.tv/videos/1640471302?t=0h59m23s
And if you skip fast forward to the following meetings (link displays 2nd meeting, so it should be cleared already), the target did not lose it's role (Jackal). 

Same issue happens sometimes with other players as well. Erase just doesn't work well anymore, maybe it's related to the tools added to track un-shootable crewmates for Eraser.

**Comment by K3ndoo** [comment]
'Cause you can't erase the Jackal.
