### ISSUE TITLE
[Bug Report] The Game doesn't start with Windows 11

### ISSUE THREAD

**Issue by xreflux** [TheOtherRolesAU/TheOtherRoles#421]
After release of The Other Roles 4.2.0 I deleted my old Among Us (modded with Version 4.1.7) from Steam and also deleted the Among Us folder in (Steam/Steamapps/Common/AmongUs). Reinstalled the Game (after restart) and modded it with Version 4.2.0.
After clicking the play buttons nothing happens - shortly there is the option to click stop and in the library it says running but nothing else happens and after this i can click play again.

**Comment by rayanKanawati** [comment]
Pour ma part le jeu ce lance sur windows 11 mais freeze très souvent en game

**Comment by xreflux** [comment]
I cant even start it

Am Do., 10. Nov. 2022 um 22:02 Uhr schrieb rayanKanawati <
***@***.***>:

**Comment by K3ndoo** [comment]
Would be nice, if you could attach a screenshot of that "play again" button (or whatever it is/says).

**Comment by xreflux** [comment]
I'm sorry. Its not "play again". After i click "play" nothing happens and "play" switches so "stop". After a few seconds the "play" button appears again.

**Comment by VoetbalKijk** [comment]
go to windows 10

**Comment by Elujla** [comment]
This can be fixed with clearing TEMP folder (temporary files).

**Comment by xreflux** [comment]
did not work

**Comment by Herobrine58529** [comment]
I have the same problem but with windows 10
