### ISSUE TITLE
[Bug Report] Freeze with Windows 11

### ISSUE THREAD

**Issue by rayanKanawati** [TheOtherRolesAU/TheOtherRoles#422]
**Describe the bug**
I can launch the game with windows 11 without any problem but when I am in game I have a lot of freeze

**System (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Among Us Version [e.g. v2022.10.25]
 - TheOtherRoles Version [e.g. v4.2.20

**Comment by K3ndoo** [comment]
This should not have anything to do with Win11, those freezes/lags occur on Win10 too. Sadly, this is nothing we can fix if I'm informed correctly.
