### ISSUE TITLE
[Bug Report] Medium Lover can read dead info early

### ISSUE THREAD

**Issue by Zirkusaffe** [TheOtherRolesAU/TheOtherRoles#423]
**Describe the bug**
When you are Medium and get the modifier Lover, you can read the info from questioning a dead ghost early by opening the Lover chat midgame.

**To Reproduce**
1. Be medium & lover at the same time
2. Question a ghost
3. Open the Lover chat

**Expected behavior**
The info shouldn't be in the chat until the next meeting started.

**System (please complete the following information):**
 - OS: Windows 10
 - Among Us Version v2022.10.25s (build num: 2449)
 - TheOtherRoles Version 4.20

**Comment by K3ndoo** [comment]
This has been there since we added the Lover chat. Nothing we will fix in the near future.

Thanks for the report though!
