### ISSUE TITLE
[Bug Report] Shifter + Medic interaction

### ISSUE THREAD

**Issue by DracoL1ch** [TheOtherRolesAU/TheOtherRoles#424]
A Medic with Shift modifier can protect and shift the same person. Result - completely unkillable person.

**Comment by Elujla** [comment]
Actually, Medic and Shifter as different people worked like this for many releases. 
A Medic Shifter can also die if he shifts with the wrong person (depending on chosen settings).
This gives new possible plays. Even with Evil Guesser setting to not pierce the medic shield.
I personally don't consider this as a bug.

**Comment by K3ndoo** [comment]
Not a bug though.
