### ISSUE TITLE
[Bug Report] Ping Rapidly Increases When Using TheOtherRoles

### ISSUE THREAD

**Issue by BMOTheGhost** [TheOtherRolesAU/TheOtherRoles#427]
**Describe the bug**
When joining North American servers, me and some fellow players _(using BetterCrewLink which may be part of the issue, I don't think so though due to crewlink not being hosted on Among Us servers)_ will rarely cause many of the players in the lobby to see their ping rapidly increase until about 5000ms, and then get disconnected from pings the server couldn't respond to.

**To Reproduce**
1. Join North American Servers Using TheOtherRoles
2. Host or join a lobby
3. Very small chance for your ping to start rapidly increasing until you get booted.

**Expected behavior**
The ping counter will rapidly start increasing until about 5000 or 6000 ms, then you will get booted due to the server not being able to respond to pings.

**System (please complete the following information):**
 - OS: Windows 10
 - Among Us Version: Latest/v2022.10.25s
 - TheOtherRoles Version: v4.2.0

**Additional context**
This problem rarely occurs, but happened to me and some other players several times within the past few days. I don't know if this is a recent problem, or a long lasting one that nobody has reported for some reason. It may take a while to reproduce, due to the inconsistency of it.

**Comment by ChristianKreuzberger** [comment]
We are seing a similar behaviour on EU, without BetterCrewLink.
Could it be related to an update of servers (among us 2022.12.x has been released)?
