### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by MaskdKing** [TheOtherRolesAU/TheOtherRoles#428]
Since the Update for Hide and Seek, neither Other Roles nor Town of Host has worked.In the Mod Launcher the Mod is not displayed in Town of Host. Please fixes that

**Comment by airpigeon24** [comment]
Yeah mine also is not working. I wasn't sure if it was due to the among us update or an issue on my end. Is the among us update the cause of this and will there be an updated version of the other roles coming?

**Comment by Maryversal** [comment]
1) No extra tools like "Mod Manager or "Mod Launcher"
2) There is an update soon to come for TheOtherRoles
3) Be patient

**Comment by K3ndoo** [comment]
> 

Please have a look in our Discord. There could be a solution for your problem if you're a Steam player. If you're playing on Epic, you have to wait until it's fixed.
