### ISSUE TITLE
[Bug Report] game not starting

### ISSUE THREAD

**Issue by moniekLag** [TheOtherRolesAU/TheOtherRoles#430]
**Describe the bug**
Hi, i have a problem with the mod cause when i open the game (with mod in game files) it immediately crashes but when i open the game without mod it dosen't crash.

**To Reproduce**
1. i don't really know
**Expected behavior**
crash

**Screenshots**
https://streamable.com/7j25fo (video)

**System (please complete the following information):**
 - OS: [ Windows 11]
 - Among Us Version [e.g. v2022.12.14e]
 - TheOtherRoles Version [4.2.0]

**Additional context**
game started to crash after the newest update

**Comment by moniekLag** [comment]
the overlay error does nothing to the actual game (it just makes discord overlay not work)

**Comment by ChristianKreuzberger** [comment]
Pretty sure it just doesn't work with the latest version  v2022.12.14e yet ;)

**Comment by K3ndoo** [comment]
Check our discord for a solution when using Steam. If you're using Epic, you have to wait for the mod to be fixed.
