### ISSUE TITLE
Mod doesn't work on latest among us epic games version (2022.12.14e)

### ISSUE THREAD

**Issue by CristianEduardMihai** [TheOtherRolesAU/TheOtherRoles#431]
**Describe the bug**
The latest steam version of the game is 2022.10.25s, but seems like the epic version got a pathc in update 2022.12.14e, making the two game versions uncompatible

**To Reproduce**
1. Install the game from Epic Games
2. Install the mods
3. (the game will either crash now or continue, if it does, go to step 4)
4. Try to join a game hosted by someone with the steam version
5. You will get a incompatible version error (only managed to get the game starting once, so no screenshot :( )

**Expected behavior**
The game should *start*, and if so you should be able to join a game hosted by the steam version

**Screenshots**
-

**System (please complete the following information):**
 - OS: Windows 10
 - Among Us Version: 2022.12.14e
 - TheOtherRoles Version: v4.2.0
 - 
**Additional context**
none

**Comment by K3ndoo** [comment]
We know. Please check out out Discord, if there's an update.
