### ISSUE TITLE
Cosmetics Disappear

### ISSUE THREAD

**Issue by ImmortalMonster** [TheOtherRolesAU/TheOtherRoles#435]
I uploaded the mod to my game and ran it and everything was perfect, so I decided to add a modded map that I saw one day. After I added the map I tried to run the game and it didn't work so I removed all mods and reinstalled the game. Then I reinstalled TOR and then I ran it and the only thing that didn't work was the cosmetics. I checked the files and it showed the cosmetics designs in the main section, but still didn't appear.

**Comment by K3ndoo** [comment]
Restart the mod or simply wait until they appear. :)
