### ISSUE TITLE
[New Role] Poucher

### ISSUE THREAD

**Issue by JustASysAdmin** [TheOtherRolesAU/TheOtherRoles#436]
**Is your feature request related to a problem? Please describe.**
I coded a feature request that was made in the discord.

See: https://github.com/JustASysAdmin/TheOtherRoles2/commit/18ccc06633013fe1ef43a87cea7bff88c7675470

**Describe the solution / role you'd like**
The role sees the roles of players they have killed

See: https://discord.com/channels/818086884089659412/825225643285282838/1060556843581194320

Due to differences between my fork and TOR, I cannot make a PR. Provided a specific commit instead.

**Comment by K3ndoo** [comment]
This seems to be a very boring standalone role. I guess this would fit better as a modifier, if at all.

Thanks for the "PR" though. :)
