### ISSUE TITLE
[Suggestion] Chicken Role

### ISSUE THREAD

**Issue by Nolij** [TheOtherRolesAU/TheOtherRoles#437]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution / role you'd like**
Drawing from chickens running around when their heads are cut off - the Chicken role would, upon death, be able to run around at fast speeds for a few seconds as a corpse.

**Describe alternatives you've considered**
Not adding the role? Sounds kind of boring to me.

**Additional context**
N/A

**Comment by K3ndoo** [comment]
Thanks for the suggestion!

This is not something we consider to add, since it could lead to various problems/bugs.
But don't hesitate to make another suggestion. If you do, it would be nice to use our Discord to do so, since we're gonna see it and respond there quicker.
