### ISSUE TITLE
Debug mode not working or unclear how to activate

### ISSUE THREAD

**Issue by xerminator** [TheOtherRolesAU/TheOtherRoles#439]
Steps to reproduce

- Enable DebugMode in the config
- Start up Among Us
- Create a game
- Try to use DebuggingTools

**Comment by gendelo3** [comment]
Debug mode is for developers only. It can be enabled by entering the correct passwort as the value of Debug in the config, not just true. You can set your own personal password for your build, s.t. you can enable debug mode. We do this to avoid lobby hosts or other players in online lobbies accidentally playing with debug mode.
