### ISSUE TITLE
More control in settings

### ISSUE THREAD

**Issue by DainPLay** [TheOtherRolesAU/TheOtherRoles#442]
While playing with a mod, I've always wanted more control over settings of the game, especially with regards to the guesser settings. I have already modded them in myself for me and my friends. But I also wanted to suggest my take on them to you.

1) An ability and an option to guess Lovers
2) An option to guess your Lover
3) An option to guess more thann one Lover per game
4) An option to give every Impostor Evil Guesser abilities
And also I suggest to move role-specific guesser settings from guesser menu to that role menu. Ex: "Guesser ignores medic shield" should be under Medic spawn rates, "Can guess Spy' under Spy etc.

I think these changes would make the mod more interesting for small lobbies, it defenetly did for ours!

**Comment by K3ndoo** [comment]
1. Since it's a Modifier. Won't happen.
2. Since it's a Modifier. Won't happen.
3. Since there can only be one Lover (pair), this doesn't make sense.
4. Play Guesser-Mode if you want more than 1 Evil Guesser. Having guesser options where they belong - to the Guesser - won't be touched.

**Comment by DainPLay** [comment]
I see your intentions, looks like it wont leave our lobby "^^
