### ISSUE TITLE
Other language support

### ISSUE THREAD

**Issue by DainPLay** [TheOtherRolesAU/TheOtherRoles#443]
I'm russian and personally I have no problem playing any game in English. But when it comes to Among Us, not all my friends know English perfectly, so it made their expirience with a mod very frustrating. Language barrier between them and the mod was the reason that made me look into mod's code and translate everything to russian for our lobby ':D
But it took me changing various strings all over the mod//

It would be easier if, for example, all of the translateble strings were referenced in one file. That if you want to make other language support. I can assure you with help with russian language support at least :)

**Comment by Mohab-Zedan** [comment]
Please support the names in other languages

**Comment by K3ndoo** [comment]
We were working on a translation, but it's currently too much work to implement. MAYBE it will be added in the future.
