### ISSUE TITLE
Blackmailer Role

### ISSUE THREAD

**Issue by DainPLay** [TheOtherRolesAU/TheOtherRoles#444]
The Role form the mod "Town Of Us", I know, but I love it. I don't want to compare, but I want to say that TheOther Roles has an ideal role balance between controllable chaos and traditional Among Us mindgames, which is missing inn TOU in my opinion. You know what mod do I prefer and I think that it missinng the Blackmailer role as it is a great idea for among us impostor role. 
I added Blackmailer role in myself already by modifying yoyr mod and basing it on witch's code. But I called it "Manipulator" and I it plays really well in lobbies.

I don't know mod developer relations and I don't know if it is that simple to have others role ideas in your mod or not, but just sayin'

**Comment by K3ndoo** [comment]
This is whether an issue or pr, nor a suggestion, so I will close it. If you want to suggest something. Please head over to our Discord and have a look in "creat-suggestions". :)

**Comment by DainPLay** [comment]
Oh ok sorry
