### ISSUE TITLE
Pirate Role

### ISSUE THREAD

**Issue by DainPLay** [TheOtherRolesAU/TheOtherRoles#445]
That one is an original idea for a neutral role that we came up with in our lobby one evening.
Team: NEUTRAL
Win condition: Give black spots to players and wait for enogh of them to die.
Active abilities: BLACK SPOT - marks other player for death. Has 0 uses at the first round and grants one use after each meeting. 
Marked players show up as marked to pirate all the time and to everybody else when these players are dead. For Impostors to fear the Pirate win.
Besause of the tricky win condition, Pirate can win after its death.
That's it. 

We first thought that it would be too random or too stupid to play at, but then it striked that in order to win you have to know who is cleared and who will die next to give them black spot. And also it will create unique scenarios for all the other roles ;)

**Comment by K3ndoo** [comment]
We won't add another Neutral killer in the near future, if at all. But thanks for your suggestion though! :)

**Comment by DainPLay** [comment]
But he can't kill...
