### ISSUE TITLE
No settings in the Lobby Menu

### ISSUE THREAD

**Issue by ngnlTeto** [TheOtherRolesAU/TheOtherRoles#447]
**Description**
If I open the settings of the lobby I get empty white screens.

**Steps to reproduce the behavior:**
1. Do the common installation
2. Host a new game
3. Go to the desk in the waiting lobby
4. Switch to a custom rider
5. Get empty settings

**Expected behavior:**
I guess there should be settings to control the role distribution.

**Screenshots:**
![image](https://user-images.githubusercontent.com/75142172/228599988-310f66b5-2d32-4219-a465-625c2e302e0e.png)
![image](https://user-images.githubusercontent.com/75142172/228600144-8c8675a1-30f1-4173-9648-35a2d267a0b6.png)
![image](https://user-images.githubusercontent.com/75142172/228600172-13f25f57-8c0f-4fa8-87dd-3d540e64ae7e.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Among Us Version v2023.3.28s
 - TheOtherRoles Version v4.3.0

**Comment by Pikafyou** [comment]
Have that problem too...

**Comment by gendelo3** [comment]
The mod will be updated soon.

For so long use the beta branch of among us, public previous in steam. (No solution for epic users, sorry)

If you need additional help you can find us in our discord.

**Comment by K3ndoo** [comment]
What Gendelo said. :)
