### ISSUE TITLE
[Suggestion] Hide and Seek Settings

### ISSUE THREAD

**Issue by basarama** [TheOtherRolesAU/TheOtherRoles#448]
When playing TOR Hide and Seek some settings are hidden or lacking compared to the regular modes.

**Describe the solution you'd like**
Ideally Hide and Seek settings would include base settings or a custom setting to allow player speed to be changed. Also if map selection could enable an option for random map selection similar to the Guesser that would be amazing.

**Comment by Mitchellmw** [comment]
I love these suggestions - seconded!

**Comment by alexbajc** [comment]
These suggestions are a must!

**Comment by K3ndoo** [comment]
Open a "normal" lobby. Change your player speed to the speed you want to play with. Go back and open a Hdie 'n Seek lobby.

You're welcome.

**Comment by basarama** [comment]
@K3ndoo I'm aware of how to work around changing player speed but it's pretty disruptive if someone asks to change the speed that you have to leave -> make a lobby - > change a setting -> leave -> make a lobby - > share code -> wait for other to join new lobby.

**Comment by Mitchellmw** [comment]
I like to change player speed between rounds, which the workaround makes a bit more challenging. Thank you for suggesting the workaround though @K3ndoo! I appreciate your thoughts and creativity.

**Comment by K3ndoo** [comment]
We added it to our list though. But not sure, if or when we will/can add it. :)
