### ISSUE TITLE
[Bug Report] Game with spy, didn't trigger lover win condition, spy can't be guessed

### ISSUE THREAD

**Issue by higps** [TheOtherRolesAU/TheOtherRoles#450]
**Describe the bug**
Lover win condition doesn't trigger properly.

**To Reproduce**
Steps to reproduce the behavior (See screenshot for reference):
1. Marius is Impostor and lover with Ida H (swapper)
3. Johansen is jackal and makes Marius sidekick
4. Truls is an impostor and kills a player
5. There are 4 players remaining. Fredrik (Spy), June(Sheriff), Marius (Jackal Lover), Ida H (Swapper Lover)
6. Marius kills June
7. Truls (dead impostor) wins by himself

**Expected behavior**
Lovers should have won as it was 2 lovers  and 1 crew left.

Spy cannot be guessed as it's not in the guess list.

**Screenshots**
If applicable,
![Among_Us_2023-04-13_21-07-52](https://user-images.githubusercontent.com/59850204/231860962-79f55147-9633-479e-b8c6-0fec0579155e.jpg)
 add screenshots to help explain your problem.

**Additional context**

**Comment by K3ndoo** [comment]
1. You forgot some steps, but this bug probably occurs when the option is turned on that you can sidekick an Imposter. Nothing we can fix easily and if, not in the near future.
2. You can't guess the Spy 'cause it's turned off in the Guesser settings (by the lobby host).
