### ISSUE TITLE
INSTA KILL BUG

### ISSUE THREAD

**Issue by Brenko317** [TheOtherRolesAU/TheOtherRoles#455]
I have A Bug Where As Sherrif And Jackal I Instantly Kill As Soon As The Kill Countdown Is Up. Those Roles Specifically.
Some Of The Other Roles Also Instantly Use Their Ability.

It Can't Be helped By Unbinding Your Keys To Nothing.
It's Maybe Something To Do With The h Key Being Bugged And Using These Things While Not Being Binded.

**Comment by K3ndoo** [comment]
What keyboard layout do you use?

**Comment by Brenko317** [comment]
You Mean Azerty Or Qwerty? I Use Azerty.
