### ISSUE TITLE
[Suggestion] Allowing more flexibility to guesser mode

### ISSUE THREAD

**Issue by Cameron-Carra** [TheOtherRolesAU/TheOtherRoles#457]
**Is your feature request related to a problem? Please describe.**
My lobby has been trying to play with the Guesser Mode, but we've noticed a problem:
- It's impossible to put 0 crew and 0 neutral guessers (1 seems to be the minimum)

**Describe the solution / role you'd like**
It would be nice to be allowed to remove the option completely for crews and neutrals.

Thank you

**Comment by K3ndoo** [comment]
Well. You can play the Classic mode and have only one Evil Guesser.
