### ISSUE TITLE
[Bug Report] Eraser can see Jackal not being Erased

### ISSUE THREAD

**Issue by DracoL1ch** [TheOtherRolesAU/TheOtherRoles#460]
Erase should put Jackal into 'erased' list without Erasing them. 

Currently WIth Guesser mode Eraser can see Aim button not being hidden from Jackal. Any other erased crewmate has it hidden.

**Comment by gendelo3** [comment]
Fixed with the new version. Eraser can no longer guess Jackal and Sidekick after fake "erasing" them
