### ISSUE TITLE
[Jester can't get voted out option]

### ISSUE THREAD

**Issue by higps** [TheOtherRolesAU/TheOtherRoles#462]
**Is your feature request related to a problem? Please describe.**J
jester is close to impossible to win in a game where everyone is a guesser. It comes down to pure luck (way more than usual). If everyone else blames the jester and the impostors know it, they will guess Jester every time, making it completely unwinnable in certain scenarios. It would make more sense and add more risk to make the jester not guess-able similar to Snitch. This would also lead to impostors making jester plays for more fun games.

**Describe the solution / role you'd like**
Similar to Snitch, Add the option to make the jester immune to be guessed in meetings

**Comment by DracoL1ch** [comment]
If you use any other tactic rather than standing on a body and making everyone believing you're the killer, thats not the guesser what is problem. Does Your lobby always test everyone who about to be voted out?
Snitch HAS to reveal his role in order to be useful, Jester doesnt have to.

**Comment by K3ndoo** [comment]
What Draco said. Seems to be a YOU-problem (your lobby or whoever) and not a ROLE-problem.
