### ISSUE TITLE
[Suggestion] Add 'Good Guesser can't guess until X tasks done' option

### ISSUE THREAD

**Issue by DracoL1ch** [TheOtherRolesAU/TheOtherRoles#463]
Currently with Guesser mode (the only really playable w/o everyone just shouting their role blatantly) as an impostor you're afraid of using your abilities from the start. As soon as they narrow down suspect list to 2-3 players, it's pretty easy to become a victim of a guesser who has no fear - if good guesser misses, lobby just kicks the another suspect.

This scenario directly affects Witch, Ninja, Morphling, Bomber, Eraser.

My idea is to add option 'Good guesser can only guess after doing X tasks' so you won't play outnumbered from the very start as an impostor because your partner dies immediately because he used his ability.

**Comment by tartsharpcobra** [comment]
nice guesser not good guesser

**Comment by gendelo3** [comment]
It's on our list - not sure if or when it will happen. Ty for the suggestion.
