### ISSUE TITLE
I cant even open the game???

### ISSUE THREAD

**Issue by AMONGUSMODCOMPLAINT** [TheOtherRolesAU/TheOtherRoles#464]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Among Us Version [e.g. v2021.11.15s]
 - TheOtherRoles Version [e.g. v3.3.3]

**Additional context**

**Comment by K3ndoo** [comment]
Just wait until the mod is working again. If you referring to the normal Among Us, please contact Innersloth.
