### ISSUE TITLE
Missing roles

### ISSUE THREAD

**Issue by StomaticMonk** [TheOtherRolesAU/TheOtherRoles#466]
I've extracted the mod from the zip folder and placed them into the among us folder properly, but when I launch the game only four of the new roles show up.  Have I messed up somewhere, am I missing part of the mod or am I overlooking something in the game settings?

**Comment by gendelo3** [comment]
There could be many issues, probably your installation wasn't done correctly. There should be a big "TheOtherRoles" banner in your main menu. 

There are a couple of mistakes that often happen to new users:

Make sure you downloaded the relase not the source code.

Make sure you dont extract to the wrong folder.

**Comment by StomaticMonk** [comment]
Ok. I'll check all that out and see. Thanks!
