### ISSUE TITLE
[Suggestion] New setting to prevent neutral roles from being lovers.

### ISSUE THREAD

**Issue by VsolZ** [TheOtherRolesAU/TheOtherRoles#467]
**Is your feature request related to a problem? Please describe.**
Im playing daily with an active group, however we run into the issue that games  with jester (the only neutral role with our settings) and a crewmate being lovers are not balanceable for us. If the jester plays for a crew win the unlimited vision makes it too easy to identify imposters, if he does not then his lover can not win.

**Describe the solution / role you'd like**
A setting that prevents neutral roles from being lovers. (similar to the existing settings: imposters cannot be lovers)

**Describe alternatives you've considered**
Make the crewmate lover win if his jester lover gets voted out, make the jester be unable to win unless they get voted out.

**Additional context**

**Comment by K3ndoo** [comment]
"(similar to the existing settings: imposters cannot be lovers)" Such a setting doesn't exist. But I guess you mean, you could turn down the percentage?

"Make the crewmate lover win if his jester lover gets voted out, make the jester be unable to win unless they get voted out."
But the Jester still has it's own win condition, when getting voted out and if they survive with their Lover, then they should lose the game? Doesn't make sense. There would never be a reason for a Crewmate Lover to not call that they're Lover with the Jester. You need to decide as a Crewmate Lover if you want your Jester Lover to win or not.
