### ISSUE TITLE
kill button not working after installing the other roles mod.  No other mods installed. Among Us version 2023.7.12s(build nim: 3365)

### ISSUE THREAD

**Issue by bb31313** [TheOtherRolesAU/TheOtherRoles#470]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Among Us Version [e.g. v2021.11.15s]
 - TheOtherRoles Version [e.g. v3.3.3]

**Additional context**

**Comment by K3ndoo** [comment]
Open one issue should be enough. Will be continued in issue #471
