### ISSUE TITLE
kill button not working after installing the other roles mod.  No other mods installed. Among Us version 2023.7.12s(build nim: 3365), The Other Roles v4.3.4

### ISSUE THREAD

**Issue by bb31313** [TheOtherRolesAU/TheOtherRoles#471]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Among Us Version [e.g. v2021.11.15s]
 - TheOtherRoles Version [e.g. v3.3.3]

**Additional context**

**Comment by bb31313** [comment]
Has this issue been resolved? What do I need to do to fix the problem?

**Comment by gendelo3** [comment]
This bug is known in free play (practise mode) but it should not be present in real games. Let us know if the issue happens in real games.
