### ISSUE TITLE
[Bug Report] Disconnect all  time and kicked auto

### ISSUE THREAD

**Issue by JeanAU** [TheOtherRolesAU/TheOtherRoles#473]
**Describe the bug**

**Hey i installed TOR on among us and i wante play when i choose MEU and join a lobby get you kicked or disconnect**

**To Reproduce**
1. Go to 'MMOnline'
2. Click on 'Server MEU'
3. Join a lobby 

**Expected behavior**

**Screenshots**
here a screenshot :  ![proof](https://github.com/TheOtherRolesAU/TheOtherRoles/assets/139503669/6294acba-53a2-4205-84dd-22a3e20ba4f3)

i get this screenshot when i join a lobby

**System (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Among Us Version [e.g. v2023.7.12s]
 - TheOtherRoles Version [e.g. v4.3.4]
 

**Additional context**

**Comment by K3ndoo** [comment]
Ask the host to open up another lobby.

**Comment by JeanAU** [comment]
why did u close

**Comment by K3ndoo** [comment]
'Cause I told you the solution to your problem.

**Comment by JeanAU** [comment]
this is not a solution i try many and i forgot to tell you sometime i can join lobby but when game start i disconnect is there any solution for this

**Comment by K3ndoo** [comment]
Get better internet I guess. Can't help you any further than that.
