### ISSUE TITLE
[Suggestion] Display last game roles even after exiting to lobby

### ISSUE THREAD

**Issue by antarctician** [TheOtherRolesAU/TheOtherRoles#475]
**Is your feature request related to a problem? Please describe.**
After a game finishes, I can see everyone's roles. (I'm very glad this feature exists). However, there's usually some pressure to go back to the lobby as soon as possible, as I don't want other people to wait for me or start without me. So, I typically can't examine everyone's roles and other stats as much as I'd like.

**Describe the solution / role you'd like**
It would be great to be able to see everyone's roles of the last game at least until the next game starts. (So, in the lobby too).
When in lobby, the left side is already taken by the lobby settings, so I see two ways to implement this:
1) Add a button to display the roles of all players in the last game.
2) Add another "page" with the info to the left panel.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by gendelo3** [comment]
I put this on our board, don't know if or when we will implement it.
