### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by REY11212** [TheOtherRolesAU/TheOtherRoles#477]
![image](https://github.com/TheOtherRolesAU/TheOtherRoles/assets/146541040/9b078d27-c222-40bb-9c9d-2ee8781800af)
I dont see Hats steam versoin

**Comment by gendelo3** [comment]
Solution:

1. Start the game, let it run for 10 minutes (hats will download in the background).

2. Restart the game
3. Check if the hats show up, if not: goto 2.
