### ISSUE TITLE
my macafee keeps making the powerselhl unit break pls fix

### ISSUE THREAD

**Issue by redpikminn** [TheOtherRolesAU/TheOtherRoles#478]
it says its a virus

**Comment by Peybro** [comment]
There's a pretty simple workaround for this: 
1) uninstall mcafee
2) done


No, seriously, most anti virus programs do more harm than good. If you only open files from trustworthy sources and turn on your head when you see links in emails and check the mails beforehand, you don't really need an antivirus. They slow down your system and possibly even sell meta data about you... 
Windows Defender also reliably finds threats and is better embedded in the system.

But if you really want to keep using Mcafee, you can exclude certain folders from being scanned: [https://www.mcafee.com/support/?articleId=TS102056&page=shell&shell=article-view](https://www.mcafee.com/support/?articleId=TS102056&page=shell&shell=article-view)

**Comment by K3ndoo** [comment]
Already reported them to McAfee and Windows (Defender). We can‘t do much more than that.
