### ISSUE TITLE
Banning a player is not possible

### ISSUE THREAD

**Issue by Peybro** [TheOtherRolesAU/TheOtherRoles#480]
https://github.com/TheOtherRolesAU/TheOtherRoles/blob/39c3e3d21c17d30f77f0e86f5f4720142c5cbf80/TheOtherRoles/Modules/ChatCommands.cs#L28-L29

`"/ban RandomName".substring(6)` will always result in the name missing its first letter.

**Comment by K3ndoo** [comment]
The lobby host still has the option via chat (not command).

**Comment by gendelo3** [comment]
Will be fixed in the next update - closing this and the related PR
