### ISSUE TITLE
[Suggestion] The "Spectre"

### ISSUE THREAD

**Issue by 9990765439** [TheOtherRolesAU/TheOtherRoles#483]
Introducing the "Specter" – an Impostor with the ability to temporarily phase through walls and obstacles. The Specter can activate their phasing ability, allowing them to move through barriers, vents, and locked doors for a limited duration.

This unique power enables the Specter to navigate the map quickly and access areas that are typically restricted to other players. The catch is that while phased, the Specter is still visible to other players or invisible "adjustable in the settings".

**Comment by K3ndoo** [comment]
This got suggested many times before and we think we won't add such a role.
Thanks for the suggestion though.
