### ISSUE TITLE
[Suggestion] The "Butcher"

### ISSUE THREAD

**Issue by 9990765439** [TheOtherRolesAU/TheOtherRoles#485]
**Is your feature request related to a problem? Please describe.**
The existing roles lack a visceral and direct way for Impostors to affect Crewmates.

**Describe the solution / role you'd like**
Introduce the "Butcher." The Butcher can disable a Crewmate's ability to perform tasks temporarily by sabotaging their tools. This creates a direct and tangible impact on Crewmates' abilities, adding a new layer of strategy for Impostors.

**Describe alternatives you've considered**
An alternative could be a role that disrupts tasks in a different manner, but the Butcher's role provides a more immersive and immediate interference.

**Additional context**
The Butcher's role aims to offer Impostors a more hands-on approach to hindering Crewmates, fostering a sense of urgency and chaos during the game. This disruption adds a unique challenge for Crewmates to overcome and introduces a dynamic element to task completion.

**Comment by K3ndoo** [comment]
Thanks for the suggestion, but we don't think it fits with the current roles and gameplay of our mod.
