### ISSUE TITLE
subway worker

### ISSUE THREAD

**Issue by fireoss** [TheOtherRolesAU/TheOtherRoles#486]
**Is your feature request related to a 

In the current game, you move through a vast map in one direction, and the background changes don't feel fresh and you keep moving through the same map over and over again.
I think you will feel a little empty.

**Describe alternatives you've 

There are five main characteristics of this position.

①. Can only be used by Crew faction.
You can create up to 3 vents on the field. However, the distance between vents can only be created within 3 areas.

② If you connect two or more vents, you can pass tickets to other players who come in contact with them.
Crew members with tickets can use the vents created in the same manner as they like at any time.

③Although it is not visible to other factions, a sound is made when creating or using a vent.
You can also set the number of people to whom tickets can be distributed.

④If the ticket is distributed to a faction other than the Crew faction, it will self-destruct, but the vent created will remain as it is. Therefore, players who have been distributed tickets in advance can use the created vents.

⑤Also, when you have created one or more vents, you can delete the created vent so that you can create a new vent.
A cooldown time is required when creating and using a vent, which can be set.
Although it is invisible to other factions, a sound is made when creating or using a vent.

**Additional context
Please create an item to pass a ticket and an item to delete an existing event/create an event.

**Comment by gendelo3** [comment]
I feel like this is too similar to the Portalmaker.
