### ISSUE TITLE
[Bug Report] Map: Fungal | Out of the map with anti-tp

### ISSUE THREAD

**Issue by EDWernars** [TheOtherRolesAU/TheOtherRoles#487]
**Describe the bug**
When you sitting on the ladder, it is possible to glitch out of the map when you have anti-tp and meeting is called. I had this problem by the ladder to communications.

**To Reproduce**
1. Go to communications
2. Sit on ladder, wait for report (with anti tp modifier)
3. meeting done and you can go outside of the map.

**Expected behavior**
Teleport to the nearest point of the ladder where you are.

**System (please complete the following information):**
 - Windows 11
 - newest version
 - newest version

**Comment by gendelo3** [comment]
There is a bug in all maps with ladders / platforms or even if you stand to close to a wall. If you're anti-tp, try to avoid that. Anyone who does this in purpose should be kicked from your lobby.
