### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Dxgamer7405** [TheOtherRolesAU/TheOtherRoles#488]
mod not working.
tested on win 11
i just put the dll on bepinex/plugins folder and executed my among us (steam)

**Comment by Dxgamer7405** [comment]
tested on 2023.11.28s among us version and with latest version of tor

**Comment by Mettwasser** [comment]
Can confirm, same thing for me.
I can get into the game no problem, but unfortunately I don't see the roles etc. in the Game Settings. 
W11 here aswell.
