### ISSUE TITLE
[Ask] How to get in debug mode?

### ISSUE THREAD

**Issue by EDWernars** [TheOtherRolesAU/TheOtherRoles#489]
I see that you can press F to spawn bots and L to terminate the game. but how can I go into the debug mode?

**I changed the code**
DebugMode = Config.Bind("Custom", "Enable Debug Mode", "<password>");
 private static readonly string passwordHash = "<new hash of password>";

^ but above didnt work .

I also tried to command it out, but when im spawning bots and then join the game It would infinity loading without any vision of a playable game (it would just stay on the loading game, but I can hear sound of walking).

When terminate the game then it would just do the starting animation and its done.

**Comment by gendelo3** [comment]
Debug mode is currently not maintained. If you change the code you can ofc ignore the pw hash thingy, otherwise you need to set the password-hash to something you like, and enter the same password in the config file.
