### ISSUE TITLE
Steam Authorization Works

### ISSUE THREAD

**Issue by raeghost** [TheOtherRolesAU/TheOtherRoles#493]
When launching the mod after extracting all the files to a new folder and adding the among us browsed files it gives me an error message and wont let me link my among us account and then it wont let me play the game dunno if i downloaded wrong or what ive been doing this way forever

**Comment by gendelo3** [comment]
Make sure you have steam running in the background

raeghost ***@***.***> schrieb am So., 3. März 2024, 11:56:

**Comment by raeghost** [comment]
i did @gendelo3
