### ISSUE TITLE
Killing someone in Prophunt crashes the round and everyone except the killer and the one who got killed gets kicked

### ISSUE THREAD

**Issue by Peybro** [TheOtherRolesAU/TheOtherRoles#494]
**Describe the bug**
Title says it basically: in Prophunt when the seeker kills any prop, the round crashes and everyone except these two will be kicked from the lobby.

**To Reproduce**
1. Open a lobby
2. Type in chat '/gm prop'
3. Let people join
4. Click start
5. Wait until a seeker kills a prop

**Expected behavior**
Prop should be dead or (depending on setting) another seeker/killer.

**System (please complete the following information):**
 - OS: Windows 11
 - Among Us Version: v2024.3.5s (build num: 3971)
 - TheOtherRoles Version: v4.5.2

**Comment by gendelo3** [comment]
fixed in [9c36355](https://github.com/TheOtherRolesAU/TheOtherRoles/commit/9c36355058321e57ad8088f68393673c2009aa05)
