### ISSUE TITLE
[Bug Report] Roles shown even when their percentage is 0%

### ISSUE THREAD

**Issue by Elekam** [TheOtherRolesAU/TheOtherRoles#495]
**Describe the bug**
Me and my friends see roles for ourself even when that role is at 0%, and we cant use the abilities or anything. It seems like we are just crewmates but get shown a random role at the start of the game

**System (please complete the following information):**
 - OS: Windows 10
 - Among Us Version: not sure
 - TheOtherRoles Version: v4.5.2

**Comment by Elekam** [comment]
Also, people that have an actual role sometimes get shown a different role at the start

**Comment by Vangaaa23** [comment]
Check, in the section “The Other Settings”, how many are the minimum crewmate/impostor/neutral roles assigned (it’s 15 by default). If there are more minimum roles than the ones you selected, the game will fill up with random roles till it reaches the minimum number required.
For example if 5 minimum crewmates roles are required and you have only 3 selected with 100% probability, the game will add 2 more random crewmates roles, even if the probability of all other roles is 0%.

**Comment by gendelo3** [comment]
It might also be connected to a certain day at the beginning of the current month, and a very funny mod dev team trying to bamboozle its playerbase...

**Comment by Elekam** [comment]
Thanks, I will check next time we play soon and check it out. Will update, with luck I will close this.

**Comment by gendelo3** [comment]
You can also turn it off by turning off "Enable Special Mode" at the TOR general tab at the lobby settings (laptop)

**Comment by Vangaaa23** [comment]
What does “Enable special mode” do?

**Comment by gendelo3** [comment]
It turns on or off the April's Fools mode of TOR. The option is only available for one week after the 1st of April.

**Comment by Vangaaa23** [comment]
Oh, ok. Thank U! :)

**Comment by Elekam** [comment]
It seems to have been the April Fools update, thanks for the help everyone :)
