### ISSUE TITLE
[Suggestion] Kill animation for guesser during meetings

### ISSUE THREAD

**Issue by Vangaaa23** [TheOtherRolesAU/TheOtherRoles#496]
When Guesser kills someone (or commits suicide for a wrong guess) during meetings, there is no kill animation. I suggest, in order to make that kill more evident and funnier, to implement an animation where everyone sees the killed player getting killed by himself.
Thank you!

**Comment by gendelo3** [comment]
We do have the sound and the Player Vote Area going gray - I dont think we'll add a different animation to it just now.
