### ISSUE TITLE
Mods not running on Mac using Whiskey 

### ISSUE THREAD

**Issue by Vangaaa23** [TheOtherRolesAU/TheOtherRoles#497]
Hi everyone, I’m trying to play modded Among Us on my Mac Pro M1 using Porting Tool and Whiskey. I bought Among us on Steam and downloaded Among Us. The game works perfectly, when I open it through Steam, but when I add the mod files to Among Us folder, it still opens the Vanilla game without mods.

**Comment by whichtwix** [comment]
perhaps look into proton and following this https://docs.bepinex.dev/articles/advanced/proton_wine.html

**Comment by gendelo3** [comment]
I am sorry but we only offer support for Windows: All other OS and emulators are more difficult to get running. I don't know if it is possible to get it running on ARM Macs. Feel free to comment a solution even after I close this issue.

**Comment by Vangaaa23** [comment]
Ok, thank you! :)
