### ISSUE TITLE
[Bug Report] Crewmates can teleport Imposters to vents they've been in before

### ISSUE THREAD

**Issue by Grovespaz** [TheOtherRolesAU/TheOtherRoles#498]
**Describe the bug**
If an imposter has been in a certain vent before, under certain circumstances, when a crewmate opens a vent to clean it, the imposter will get teleported across the map to "jump" out the vent.

**To Reproduce**
Steps to reproduce the behavior (though not conclusively):
1. Imposter goes into a vent
2. Imposter exits the vent
3. Crewmate opens vent to clean it
4. Surprise imposter!

**Expected behavior**
If an imposter is not in a vent, a crewmate should not be able to pull them out of that vent.

**Video**
[Here's a Twitch clip of it happening.](https://clips.twitch.tv/RespectfulBashfulHedgehogShadyLulu-1Fn7meJxz_1iJMAP)

**System (please complete the following information):**
 - Windows 11
 - Among Us 2024.3.5s
 - TheOtherRoles v4.5.2

**Additional context**
We've seen this happen four times in our lobbies over the course of three evenings

**Comment by Grovespaz** [comment]
Some additional information, it may be triggered by an imposter being in the vent when a meeting is triggered the round before, can't confirm this yet though.

**Comment by K3ndoo** [comment]
This is a vanilla problem as far as I know.
Well. Happened to me on vanilla though.
