### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by youmustp** [TheOtherRolesAU/TheOtherRoles#503]
**Describe the bug**
When I open the game it crashes after a bit.

**To Reproduce**
idk

**Expected behavior**
The game to open

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 11
 - Among Us Version: v2024.6.18s
 - TheOtherRoles Version: v4.5.3

**Additional context**

**Comment by youmustp** [comment]
I tried down grading but then i got a black screen

**Comment by gendelo3** [comment]
see #502

**Comment by youmustp** [comment]
Thanks

**Comment by HelpMeNoww** [comment]
what? how do i fix it i do not understand

**Comment by mxyx0412** [comment]
> what? how do i fix it i do not understand

The mod not support version v2024.6.18.

Open Steam library.
Right-click on “Among Us” and select “Properties.”
Go to the “Betas” tab.
Choose the “public-previous” option from the drop-down menu.
Wait for the update to complete.

Additionally, delete the “settings.amogus” file located at "C:\Users\<username>\AppData\LocalLow\Innersloth\Among Us".

**Comment by HelpMeNoww** [comment]
> > what? how do i fix it i do not understand
> 
> The mod not support version v2024.6.18.
> 
> Open Steam library. Right-click on “Among Us” and select “Properties.” Go to the “Betas” tab. Choose the “public-previous” option from the drop-down menu. Wait for the update to complete.
> 
> Additionally, delete the “settings.amogus” file located at "C:\Users<username>\AppData\LocalLow\Innersloth\Among Us".

its on epic games for me

**Comment by HelpMeNoww** [comment]
> > what? how do i fix it i do not understand
> 
> The mod not support version v2024.6.18.
> 
> Open Steam library. Right-click on “Among Us” and select “Properties.” Go to the “Betas” tab. Choose the “public-previous” option from the drop-down menu. Wait for the update to complete.
> 
> Additionally, delete the “settings.amogus” file located at "C:\Users<username>\AppData\LocalLow\Innersloth\Among Us".

how do i do it in epic games
