### ISSUE TITLE
Crash when startup

### ISSUE THREAD

**Issue by HelpMeNoww** [TheOtherRolesAU/TheOtherRoles#508]
**Describe the bug**
When I open the game it crashes after a bit.

**To Reproduce**
Get the mod files in the among us files
open among us in epic games
it opens then crashes after a bit

**Expected behavior**
The game to open

**Screenshots**
![image](https://github.com/user-attachments/assets/37690d43-af88-4f07-bc53-4b1c4b4eccc8)
it says it starts running ↑
![image](https://github.com/user-attachments/assets/16b2e21d-f80d-4def-9a5d-e2e2266fde58)
this is what among us looks on taskbar when it starts to open↑
![image](https://github.com/user-attachments/assets/5b80d21f-0122-4920-8355-11630de2f847)
it closes epic games and when it crashes it starts up again ↑

**System (please complete the following information):**
 - OS: Microsoft Windows 10 Pro
 - Among Us Version 2024.3.5s
 - TheOtherRoles Version v4.5.3

**Additional context**
Me and my friend tried everything we found and did the mod dowloading a lot of times but it still wouldnt work for the both of us

**Comment by Nestoro** [comment]
Probably the same as the issue https://github.com/TheOtherRolesAU/TheOtherRoles/issues/506. The current Among us version v2024.6.18 is incompatible. If you were using steam, you could select public previous as beta to launch the previous version.

**Comment by HelpMeNoww** [comment]
Need to wait till mod is updated

**Comment by HelpMeNoww** [comment]
Mod needs to be updated
