### ISSUE TITLE
[Bug Report] Application closes itself before the game has even started

### ISSUE THREAD

**Issue by NobbiHabogs** [TheOtherRolesAU/TheOtherRoles#511]
**Describe the bug**
Game do not start.
Application gain some RAM-usage and then disappear, also "lived" longer on the first start where it went up to almost ~2 GB.
After the first start the process is just alive for like 3-4 seconds using ~20-160 MB and then close itself.

**To Reproduce**
1. Install like recommended
2. Start the game

**Expected behavior**
Starting the game instead of shutting itself down.

**Screenshots**
Screenshot 1: 
![unbenannt2](https://github.com/user-attachments/assets/61bbe1ac-68fd-4251-9685-3f52b25e34e7)

System Info:
![Unbenannt](https://github.com/user-attachments/assets/0626fa48-d46f-4efb-9830-9416d89b3569)

**System (please complete the following information):**
 - OS: Windows 10 (19045.5131)
 - Among Us Version: 24.9.4s build 4561 (public-previous)
 - Among Us Version: 24.10.29s build 4815 (live)
 - TheOtherRoles Version: 4.6.0

**Additional context**
An older Version i had (about 1 year ago) isn't working either.

**Comment by Crispy0000** [comment]
is there no fix to this? its whenever I highlight everything from theotherroles zip folder onto my among us folder that it does this

**Comment by gendelo3** [comment]
> * Among Us Version: 24.10.29s build 4815 (live)

There is your issue:

The mod is currently only compatible with Version 2024.6.18.

You can currently obtain that version by setting your Beta Branch in Among Us' Steam properties to 
"public-beta".

Then "update" the game and repeat the installation steps.

**Comment by AlbertFlorian** [comment]
> > * Among Us Version: 24.10.29s build 4815 (live)
> 
> There is your issue:
> 
> The mod is currently only compatible with Version 2024.6.18.
> 
> You can currently obtain that version by setting your Beta Branch in Among Us' Steam properties to "public-beta".
> 
> Then "update" the game and repeat the installation steps.

And for Epic Games version? Is there any fix?

**Comment by gendelo3** [comment]
> And for Epic Games version? Is there any fix?

Yes, but its more complicated. You need to run a downgrade script. We provide that and further assistance on our discord server, (see the channel "#help chat", pinned posts).

**Comment by dcoad710** [comment]
> > * Among Us Version: 24.10.29s build 4815 (live)
> 
> There is your issue:
> 
> The mod is currently only compatible with Version 2024.6.18.
> 
> You can currently obtain that version by setting your Beta Branch in Among Us' Steam properties to "public-beta".
> 
> Then "update" the game and repeat the installation steps.

So will you still be able to play with other people who are on the old version? 
If i have just installed the game wouldnt it be on the newest version? 
Or could we use the old version of the other roles?

**Comment by gendelo3** [comment]
You will all have to downgrade your game to the required version. See the comments above on how to do that.
